# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gamma_pdf <- function(x, a, b) {
    .Call('_bart3_gamma_pdf', PACKAGE = 'bart3', x, a, b)
}

r_gamma_pdf <- function(x, a, b) {
    .Call('_bart3_r_gamma_pdf', PACKAGE = 'bart3', x, a, b)
}

print_mat_subset <- function(X) {
    invisible(.Call('_bart3_print_mat_subset', PACKAGE = 'bart3', X))
}

log_dmvn <- function(x, Sigma) {
    .Call('_bart3_log_dmvn', PACKAGE = 'bart3', x, Sigma)
}

cppbart <- function(x_train, y_train, x_test, n_tree, node_min_size, n_mcmc, n_burn, tau, mu, tau_mu, alpha, beta, a_tau, d_tau, stump, no_rotation_bool) {
    .Call('_bart3_cppbart', PACKAGE = 'bart3', x_train, y_train, x_test, n_tree, node_min_size, n_mcmc, n_burn, tau, mu, tau_mu, alpha, beta, a_tau, d_tau, stump, no_rotation_bool)
}

mat_init <- function(n) {
    .Call('_bart3_mat_init', PACKAGE = 'bart3', n)
}

vec_init <- function(n) {
    .Call('_bart3_vec_init', PACKAGE = 'bart3', n)
}

std_inv <- function(A, diag) {
    .Call('_bart3_std_inv', PACKAGE = 'bart3', A, diag)
}

std_pinv <- function(A, diag) {
    .Call('_bart3_std_pinv', PACKAGE = 'bart3', A, diag)
}

faster_simple_std_inv <- function(A, diag) {
    .Call('_bart3_faster_simple_std_inv', PACKAGE = 'bart3', A, diag)
}

log_test <- function(a) {
    .Call('_bart3_log_test', PACKAGE = 'bart3', a)
}

faster_std_inv <- function(A, diag) {
    .Call('_bart3_faster_std_inv', PACKAGE = 'bart3', A, diag)
}

rMVN2 <- function(b, Q) {
    .Call('_bart3_rMVN2', PACKAGE = 'bart3', b, Q)
}

rMVNslow <- function(b, Q) {
    .Call('_bart3_rMVNslow', PACKAGE = 'bart3', b, Q)
}

matrix_mat <- function(array) {
    .Call('_bart3_matrix_mat', PACKAGE = 'bart3', array)
}

rand_unif <- function() {
    .Call('_bart3_rand_unif', PACKAGE = 'bart3')
}

